# Generated by Django 3.0.2 on 2020-01-25 17:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_culinary_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culinary',
            name='dishes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60), default=list, size=None),
        ),
    ]
